language: cpp
compiler: 
  - gcc
  
sudo: false

addons:
  apt:
    packages:
    - xsltproc
    - libxerces-c-dev
    - xsdcxx
    - libboost1.55-dev

script:
  - mkdir build && cd build && cmake .. && make
