IF( UNIX )
    SET(CMAKE_INSTALL_SO_NO_EXE "0")
  # Si la lib est dynamique
  IF( BUILD_LIBRARY_SHARED )
    INSTALL( TARGETS LidarFormat DESTINATION lib )
  ELSE()
    INSTALL( TARGETS LidarFormat ARCHIVE DESTINATION lib )
  ENDIF()

  INSTALL( FILES ${ALL_LIDAR_FORMAT_HEADER_FILES} DESTINATION include/LidarFormat )
  INSTALL( FILES ${ALL_MODELS_HEADER_FILES} DESTINATION include/LidarFormat/models )
  INSTALL( FILES ${ALL_GEOMETRY_HEADER_FILES} DESTINATION include/LidarFormat/geometry )
ENDIF()

IF( WIN32 )
  # TODO !
ENDIF()
