#################################################
###           INSTALL 						  ###
#################################################
get_filename_component(LIDARFORMAT_CMAKE_SELF_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)

IF(UNIX)
	SET(INSTALL_PREFIX "/usr/local" CACHE PATH " install path" )
ENDIF(UNIX)
IF(WIN32)
	SET(LidarFormat_INSTALL_DIR "LidarFormat")
	SET(INSTALL_PREFIX "C:/Program Files/MATIS" CACHE PATH " install path")
ENDIF(WIN32)
SET(CMAKE_INSTALL_PREFIX ${INSTALL_PREFIX} CACHE INTERNAL  " real install path" FORCE)

IF(UNIX)
    SET(CMAKE_INSTALL_SO_NO_EXE "0")
	INSTALL (FILES ${ALL_LIDAR_FORMAT_HEADER_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/include/LidarFormat)
	INSTALL( FILES ${ALL_MODELS_HEADER_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/include/LidarFormat/models )
	INSTALL( FILES ${ALL_GEOMETRY_HEADER_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/include/LidarFormat/geometry )
	INSTALL( FILES ${ALL_TOOLS_HEADER_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/include/LidarFormat/tools )
	INSTALL( FILES ${ALL_EXTERN_HEADER_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/include/extern/matis )
	SET(RELATIVE_INCLUDE_PATH "../../include/LidarFormat")
	SET(RELATIVE_INCLUDE_EXTERN_PATH "../../include/extern")
	CONFIGURE_FILE(${LIDARFORMAT_CMAKE_SELF_DIR}/LidarFormatConfig.cmake.in ${CMAKE_CURRENT_SOURCE_DIR}/LidarFormatConfig.cmake @ONLY)
	INSTALL (TARGETS LidarFormat DESTINATION ${CMAKE_INSTALL_PREFIX}/lib EXPORT LidarFormat-targets)
	INSTALL (EXPORT LidarFormat-targets DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/LidarFormat)
	INSTALL (FILES LidarFormatConfig.cmake DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/LidarFormat)
ENDIF(UNIX)

IF(WIN32)
	INSTALL (FILES ${ALL_LIDAR_FORMAT_HEADER_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/${LIDARFORMAT_INSTALL_DIR}/include/LidarFormat)
	INSTALL (FILES ${ALL_MODELS_HEADER_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/${LIDARFORMAT_INSTALL_DIR}/include/LidarFormat/models)
	INSTALL (FILES ${ALL_GEOMETRY_HEADER_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/${LIDARFORMAT_INSTALL_DIR}/include/LidarFormat/geometry )
	INSTALL( FILES ${ALL_TOOLS_HEADER_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/${LIDARFORMAT_INSTALL_DIR}/include/LidarFormat/tools )
	SET(RELATIVE_INCLUDE_PATH "../wxsgl/LidarFormat")
	CONFIGURE_FILE(${LIDARFORMAT_CMAKE_SELF_DIR}/LidarFormatConfig.cmake.in ${CMAKE_CURRENT_SOURCE_DIR}/LidarFormatConfig.cmake @ONLY)
	INSTALL(
		TARGETS LidarFormat
		EXPORT LidarFormat-targets
		ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/${LIDARFORMAT_INSTALL_DIR}/lib
		LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/${LIDARFORMAT_INSTALL_DIR}/lib
		RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/${LIDARFORMAT_INSTALL_DIR}/bin
	)
	INSTALL (EXPORT LidarFormat-targets DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake)
	INSTALL (FILES LidarFormatConfig.cmake DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake)
ENDIF(WIN32)
